set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(DEVKITPRO $ENV{DEVKITPRO})
set(CMAKE_C_COMPILER ${DEVKITPRO}/devkitA64/bin/aarch64-none-elf-gcc)
set(CMAKE_CXX_COMPILER ${DEVKITPRO}/devkitA64/bin/aarch64-none-elf-g++)
set(CMAKE_C_FLAGS "-march=armv8-a+simd -mtune=cortex-a57 -D__SWITCH__ -fPIE")
set(CMAKE_CXX_FLAGS "${CMAKE_C_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS "-specs=${DEVKITPRO}/libnx/switch.specs")
include_directories(${DEVKITPRO}/libnx/include ${DEVKITPRO}/portlibs/switch/include)
link_directories(${DEVKITPRO}/libnx/lib ${DEVKITPRO}/portlibs/switch/lib)
